<?php

namespace Automation;

use Automation\Client\Command\GitBranchesCleanByJiraCommand;
use Automation\Client\Command\TestCommand;
use Symfony\Bundle\FrameworkBundle\Console\Application;
use Symfony\Component\Console\Command\ListCommand;
use Symfony\Component\Console\Input\InputInterface;

class GitAutomationApp extends Application
{

    protected function getDefaultCommands()
    {
        // Keep the core default commands to have the HelpCommand
        // which is used when using the --help option
//        $defaultCommands = parent::getDefaultCommands();

        $defaultCommands[] = new ListCommand();
        $defaultCommands[] = new GitBranchesCleanByJiraCommand();
        $defaultCommands[] = new TestCommand();

        return $defaultCommands;
    }

    protected function getCommandName(InputInterface $input)
    {
        return parent::getCommandName($input); // TODO: Change the autogenerated stub
    }


}